[package]
name = "gsd-sys"
version = "0.1.0"
authors = ["Ian Graham"]
edition = "2018"
build = "build.rs"
description = "Bindings to GSD's C API"
license = "MIT"
keywords = ["gsd", "hoomd", "md", "io", "ffi"]

[dependencies]

[build-dependencies]
bindgen = "*"
cmake = "0.1.31"
